# Generated by Django 3.1 on 2022-07-04 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_new_worker_shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, null=True)),
                ('role_choices', models.CharField(choices=[('Начальник смены', 'Начальник смены'), ('Оператор', 'Оператор'), ('Водитель', 'Водитель')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Добавить ФИО нач. смены, оперора, водителя',
                'verbose_name_plural': 'Добавить ФИО оператором',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value2', models.CharField(choices=[('Смена 1', 'Смена 1'), ('Смена 2', 'Смена 2'), ('Смена 3', 'Смена 3'), ('Смена 4', 'Смена 4')], max_length=50, null=True, verbose_name='смена №')),
                ('value3', models.CharField(choices=[('All', 'All'), ('Шлифовка', 'Шлифовка'), ('Распиловка', 'Распиловка'), ('Пресс', 'Пресс'), ('Формовка', 'Формовка'), ('Клееварка', 'Клееварка'), ('Сушилка', 'Сушилка'), ('Стружечное', 'Стружечное'), ('Заточка', 'Заточка'), ('Дробилка', 'Дробилка')], help_text='дробилка, стружка. заточка, сушилка, клееварка, формовка, пресс, распиловка, шлифовка', max_length=500, null=True, verbose_name='Участок')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи, пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили для выбора Форм',
                'ordering': ('-value2',),
            },
        ),
    ]
